apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Phathdt/todo-manifest.git
    targetRevision: HEAD
    path: kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-todo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
