apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: dev-todo
  labels:
    app: app-deployment
spec:
  selector:
    matchLabels:
      app: app-deployment
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-deployment
    spec:
      containers:
        - name: app-deployment
          image: phathdt379/express-todo:1.5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRESQL_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRESQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: POSTGRESQL_DATABASE
          ports:
            - containerPort: 8080
              name: app-deployment
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: dev-todo
spec:
  selector:
    app: app-deployment
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
    - name: app-svc
      protocol: TCP
      port: 80
      targetPort: 8080
