apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
  namespace: dev-todo
spec:
  storageClassName: gfs
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    path: /vol1
    server: 10.105.16.114
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-claim
  namespace: dev-todo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: 'gfs'
  resources:
    requests:
      storage: 100Gi
